#!/bin/bash
# clean up
rm -rf html
mkdir html
mkdir html/docs
mkdir html/docs/api
# copy CHANGES to html
cp LASTCHANGES html/CHANGES 
# generate API documentation:
echo 'Generating API documentation...'
rm -rf mdp
cp -r ../mdp .
rm -rf mdp/demo
rm -rf mdp/test
#epydoc --html -o html/docs/api --name="Modular toolkit for Data Processing MDP" --url="http://mdp-toolkit.sourceforge.net" --graph=all --show-sourcecode --inheritance=grouped --docformat=plaintext ./mdp
rm -rf mdp
echo 'Done.'
echo 'Generating tutorial HTML and PDF...'
cd tutorial_src/
./genhtml
cd ..
echo 'Generating MDP website...'
cd html_src
python granparser.py
cp *css images/* data/* ../html
cd ..


