#!/bin/bash
TUT=$PWD/tutorial.rst

# generate latex version
TEMP=$PWD/rem
TUTL=$PWD/tutorial_latex.txt
rm -rf $TUTL
echo '============================================' > $TUTL
echo '`Modular Toolkit for Data Processing (MDP)`_' >> $TUTL
echo '============================================' >> $TUTL
echo '                                            ' >> $TUTL
echo ' This document is also available online:    ' >> $TUTL
echo ' http://mdp-toolkit.sourceforge.net/tutorial.html' >> $TUTL
echo '                                            ' >> $TUTL
cat $TUT >> $TUTL

# generate html tutorial 
# modify header
TEMP=$PWD/temp
TEMPD=$PWD/tempd
python modify_header.py > $TEMP 
TUTHTML=tutorial.html
RST="rst2html -g -t --stylesheet=styles.css" 
$RST $TEMP $TEMPD
# enclose body of $TEMP with our headers and footers
# and copy it into the right place
python remove_header.py $TEMPD $TUTHTML
rm -f $TEMP $TEMPD

# generate pdf totorial
TEMP=$PWD/temp
RST2="rst2latex -g -t " 
$RST2 $TUTL $TEMP
TUTTEX=$PWD/tutorial.tex
# adjust \includegraphics --> \includegraphics[width=0.9\textwidth]
perl -i -p -e 's/width=700/width=0.9\\textwidth/g' $TEMP
perl -i -p -e 's/width=500/width=0.9\\textwidth/g' $TEMP
perl -i -p -e 's/width=400/width=0.9\\textwidth/g' $TEMP
perl -i -p -e 's/width=450/width=0.9\\textwidth/g' $TEMP
/bin/cp -f $TEMP $TUTTEX
rm -rf $TEMP
# compile with pdflatex
pdflatex $TUTTEX > /tmp/pdflatex.log
pdflatex $TUTTEX > /tmp/pdflatex.log
# clean up
rm -rf tutorial.aux tutorial.log tutorial.out tutorial_latex.txt tutorial.tex
# copy pdf to html directory
cp tutorial.pdf ../MDP2_5_tutorial.pdf
cp $TUTHTML ../html/$TUTHTML

# generate demos
python gendemo.py
cp demo.py ../../mdp/demo/


